ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;

CREATE USER KANJI
identified BY 1234
DEFAULT tablespace USERS quota unlimited on USERS;

GRANT CREATE SESSION, CREATE TABLE, CREATE sequence to KANJI;

-----------------------------------------------------

CREATE TABLE "KANJI"."KANJI"
(
    "KANJI_NO" NUMBER(8,0) PRIMARY KEY;
    "KANJI" VARCHAR(200 BYTE) NOT NULL;
    "YOMIGANA" VARCHAR(200 BYTE) NOT NULL;
    "KOREA" VARCHAR(200 BYTE) NOT NULL;
    "CREATE_DATE" DATE DEFAULT SYSDATE
);

CREATE sequence "KANJI"."SEQ_KANJI"
minvalue 0
MAXVALUE 9999
INCREMENT BY 1
START WITH 1
CACHE 2
noorder
nocycle
NOKEEP
NOSCALE
GLOBAL;

